---
version: '1'
type: infrastructure
extras:
  tags:
    - strata

component:
  name: data_platform_access-strata
  owner: You
  description: Strata layer for data_platform_access
  personalDataHandling: none
  soxScope: False
  serviceClass: business-class
  paymentProcessing: False