---
version: '1'
type: infrastructure
extras:
  tags:
    - strata

component:
  name: template-strata
  owner: Cassini
  description: Strata layer for template
  personalDataHandling: none
  soxScope: False
  serviceClass: business-class
  paymentProcessing: False
  deploymentSystem: strata
  outOfHoursSupportRequired: False
  supportOverride:
    slackChannel: "#engineering-support"
    confluenceUrl: "https://skyscanner.atlassian.net/wiki/x/-rueJ"
